### ISSUE TITLE
Crear REST endpoint para obtener departamentos y municipios.

### ISSUE THREAD

**Issue by jharteaga** [kodigodev/kodi-online-form#10]
Esta informacion es necesaria para mostrarla en dropdown list en el formulario de Informacion Personal.

**Comment by kodigodev** [comment]
Servicio de Departamentos expuesto momentaneamente en: https://kodigo.org/dev/controller/GetDepartamento.php

Servicio de Municipios expuesto momentaneamente en: https://kodigo.org/dev/controller/GetMunicipio.php
